### ISSUE TITLE
Support for circle?

### ISSUE THREAD

**Issue by Boscop** [ThinkAlexandria/diesel_geometry#3]
I'm looking forward to using this crate with PostGIS. 
Do you have plans to support the other geometry types like circle? :)

**Comment by YetAnotherMinion** [comment]
@Boscop Yes. Do you think circle should be returned as tuple struct of `PgCircle(PgPoint, f64)` or as a struct with named fields. `PgCircle { center: PgPoint, radius: f64`

**Comment by Boscop** [comment]
Thanks. Btw, I want to store locations (and circles) as lng/lat geography type instead of geometry because I want to do queries like "finding all records R whose distance to my location is smaller than min(R.sending_radius, my_receiving_radius)" (i.e. `distance(p1, p2) < min(r1, r2)`) and create a GIST index to speed it up.

Similar to [this](https://gis.stackexchange.com/a/247131) but storing the locations as geography instead of geometry.
Can I also use this crate's `Point` type with [`GEOGRAPHY(Point)`](http://workshops.boundlessgeo.com/postgis-intro/geography.html#creating-a-geography-table) columns?

**Comment by YetAnotherMinion** [comment]
I don't know about using `GEOGRAPHY(Point)`. Right now the type is serialized in 16 bytes as double[2] ={x, y}. I do not know enough about diesel at the moment to tell if diesel checks the OID in the row description before deserializing. If that does not work, I would be happy to add specialized geography data types.

**Comment by YetAnotherMinion** [comment]
@Boscop If you happen to know where to find the OID and binary format of PostGIS types, please tell me. I have not had much luck locating them so far.

**Comment by Boscop** [comment]
@YetAnotherMinion I only found this: https://godoc.org/github.com/lib/pq/oid
It shows the OIDs for the geometry types but not sure where we can find those for geography types. Do they even have OIDs?

In that stackoverflow answer above, it uses 
```sql
CREATE TABLE example1 (
    -- ...
)
with (
    OIDS=FALSE
);
```

**Comment by YetAnotherMinion** [comment]
Hmmm, I wonder how the query is returned? I was looking at https://www.pgcon.org/2014/schedule/attachments/330_postgres-for-the-wire.pdf which describes the v3 wire format for binary data which looks to me to always send the OID. I am not sure about the text protocol though. Fortunately it is easy enough to figure out. Tomorrow I will capture some traffic with wireshark and see how Geography Points are transmitted.

**Comment by Boscop** [comment]
```sql
geo_tmp=# select oid from pg_type where typname = 'geography';
  oid  
-------
 18620
(1 row)

geo_tmp=# select oid from pg_type where typname = 'geometry';
  oid  
-------
 17978
(1 row)
```

**Comment by YetAnotherMinion** [comment]
Added support for geometry circle type in 1.3.0
