### ISSUE TITLE
Serde support

### ISSUE THREAD

**Issue by Boscop** [ThinkAlexandria/diesel_geometry#6]
Please add optional support for serde's Serialize/Deserialize traits.
Like this:
```toml
serde = { version = "1.0", features = ["derive"], optional = true }
```
```rust
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct PgPoint(pub f64, pub f64);
```

Thanks!

**Comment by YetAnotherMinion** [comment]
One limitation of the current API is I reuse the `PgPoint` type for the contents of more complex types like circle, polygon, etc...

For example, a `PgCircle` will get serialized to json as `[[x, y], radius]` and a `PgBox` will get serialized as `[[px, py], [qx, qy]]`. We are just trading additional overhead for simpler conceptually and simpler to parse.

What is your opinion for default derives on the complex types? My current position is to keep the design in the hope that users working in another language can use their libraries default derives for the type and not have to port the custom logic.

**Comment by Boscop** [comment]
default derives is fine and I would also prefer that. No need to deviate from the default derives :)

**Comment by YetAnotherMinion** [comment]
Serialization format will usually use more bytes. PgCircle for example will use two extra bytes for `[]` characters and PgBox would use an extra 4 bytes `[][]` when using more common serialization formats such as json or toml.

Fitting under a packet boundary can cause non linear savings.

**Comment by Boscop** [comment]
If one is concerned about these small overheads, one shouldn't use json anyway..
And these serialized types will be part of larger serialized types anyway..
I don't think one should impl the serde traits to optimize the json representation, that's just one format of many and can be gzipped very well..

**Comment by YetAnotherMinion** [comment]
Added in 1.3.0
